<!DOCTYPE html>
<html lang="en">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<title>Signature Generator</title>
	</head>
	<body>
<?php
	$name = $_POST['name'];
	$title = $_POST['title'];
	$cell  = $_POST['cell'];

	$namePosted = (isset($name) && !empty($name));
	$titlePosted = (isset($title) && !empty($title));
	if($namePosted && $titlePosted){
?>
<div name="signature" style="font-size:10.5pt">
	<table>
		<tr>
			<td style="border-right:1px solid #7A0000;">

				<img style="width:130px;padding:15px;" src="http://luelectricinc.com/email_assets/lu_logo_sm.png" />
			</td>
			<td>
				<div style="float:left;margin-left:10px;font-family:arial;color:#646464;display:table-cell;">
					<span style="font-weight:bold;color:#646464;"><?php echo $name; ?></span>
					<br>
					<span class="title"><?php echo $title; ?>, L.U. Electric, Inc.</span><br>
					<?php if(isset($_POST['cell']) && !empty($_POST['cell']) ){ ?>
						<span style="font-weight: bold; color:#7A0000;">C.</span> <?php echo $cell ?>
						<span style="color:#98463B;">|</span>
					<?php }?>
					<span style="font-weight: bold; color:#7A0000;">P.</span> 949-536-3200
					<span style="color:#98463B;">|</span>
					<span style="font-weight: bold; color:#7A0000;">F.</span> 714-535-3700
					<br>
					<a style="text-decoration:none; color:#646464;" href="http://www.luelectricinc.com" title="LU Electric Inc. Website">www.luelectricinc.com</a>
					<span style="color:#98463B;">|</span>
					17762 Mitchell North Irvine, CA 92614
					<br>
					<a style="text-decoration:none;" href="https://www.facebook.com/luelectricinc/" title="LU Electric Inc. Facebook Page"><img src="http://luelectricinc.com/email_assets/fb_logo.jpg"></a>
				</div>
			</td>
		</tr>
	</table>
	<div style="font-size:10px;color:#646464;width:570px">
		<hr color="#bdbdbd" size="1">
		<br>
		CONFIDENTIALITY NOTICE:<br>
		<i>
			<br>The contents of this email message and any attachments are intended solely for the addressee(s) and may contain confidential and/or privileged information and may be legally protected from disclosure. If you are not the intended recipient of this message or their agent, or if this message has been addressed to you in error, please immediately alert the sender by reply email and then delete this message and any attachments. If you are not the intended recipient, you are hereby notified that any use, dissemination, copying, or storage of this message or its attachments is strictly prohibited.
		</i>
</div>

<?php
	}
	else{
?>
		<div style="margin: 0 auto;display:table;">
			<h1>LU Electric Inc. Email Signature Generator</h1>
			<ul>
				<li>For: LU Electricinc</li>
				<li>Written by: Brett Korp</li>
				<li>Signature Design by: Cinthya Urrego</li>
			</ul>

			<div style="margin-top:100px;">
				<h4>Generator Instructions</h4>
				<p>Put your full name (First and Last) into the field labeled Employee name.<br>
				Put your full title into the position title section.<br>
				Once you are done, press submit and your signature will be generated.</p>

				<p>A Note about cell-phones: if you put one it will show up. If not, it will be omitted.</p>

				<h4>Signature Installation Instructions</h4>
				<p>Copy the email signature once it is generated by using the hotkey: ctrl + A (select all)<br>
				Then copy your email signature into your outlook signature.</p>
			</div>
			<div style="background-color:gainsboro;padding:50px;width:500px;">
				<form method="post">
					<label>Name:</label><br>
					<input style="width:100%;" type="text" name="name">
					<br><br>
					<label>Position Title:</label><br>
					<input style="width:100%;" type="text" name="title">
					<br><br>
					<label>Cell Phone:</label><br>
					<input style="width:100%;" type="cell" name="cell">
					<br><br>
					<input style="float:right;" type="submit">
				</form>
			</div>
		</div>
<?php } ?>
	</body>
</html>
