<!DOCTYPE html>
<html lang="en">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<title>Signature Generator</title>
	</head>
	<body>
<?php
	$name = $_POST['name'];
	$title = $_POST['title'];

	$namePosted = (isset($name) && !empty($name));
	$titlePosted = (isset($title) && !empty($title));
	if($namePosted && $titlePosted){
?>
	<div style="font-size: 10.5pt;">
		<div style="float:left; border-right:1px solid #7A0000;">
			<img style="padding:20px 10px 19px 10px; float:left;" src="http://luelectricinc.com/email_assets/lu_logo.png" />
		</div>
		<div style="float:left;margin-left:10px;font-family:arial;color:#646464;">
			<span style="font-weight:bold;color:#646464;"><?php echo $name ?></span>
			<br>
			<span class="title"><?php echo $title ?>, L.U. Electric, Inc.</span><br>
			<span style="font-weight: bold; color:#7A0000;">P.</span> 949-536-3200 
			<span style="color:#98463B;">|</span> 
			<span style="font-weight: bold; color:#7A0000;">F.</span> 714-535-3700 
			<br>
			<a href="http://www.luelectricinc.com" title="LU Electric Inc. Website">www.luelectricinc.com</a>
			<span style="color:#98463B;">|</span> 
			17762 Mitchell North Irvine, CA 92614
			<br>
			<a href="https://www.facebook.com/luelectricinc/" title="LU Electric Inc. Facebook Page"><img src="http://luelectricinc.com/email_assets/fb_logo.jpg"></a>
		</div>
	</div>
<?php
	}
	else{
?>
		<div style="margin: 0 auto;display:table;">
			<h1>LU Electric Inc. Email Signature Generator</h1>
			<ul>
				<li>For: LU Electricinc</li>
				<li>Written by: Brett Korp</li>
				<li>Signature Design by: Cinthya Urrego</li>
			</ul>

			<div style="margi-top:100px;">
				<h4>Generator Instructions</h4>
				<p>Put your full name (First and Last) into the field labeled Employee name.<br>
				Put your full title into the position title section.<br>
				Once you are done, press submit and your signature will be generated.</p>

				<h4>Signature Installation Instructions</h4>
				<p>Copy the email signature once it is generated by using the hotkey: ctrl + A (select all)<br>
				Then copy your email signature into your outlook signature.</p>
			</div>
			<div style="background-color:gainsboro;padding:50px;width:500px;">
				<form method="post">
					<label>Name:</label><br>
					<input style="width:100%;" type="text" name="name">
					<br><br>
					<label>Position Title:</label><br>
					<input style="width:100%;" type="text" name="title">
					<br><br>
					<input style="float:right;" type="submit">
				</form>
			</div>
		</div>
<?php } ?>
	</body>
</html>